# Copyright (c) 2024 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/ohos.gni")
import("//build/test.gni")
import("//foundation/multimedia/audio_framework/config.gni")

ohos_unittest("remote_audio_capturer_source_unit_test") {
  install_enable = false

  module_out_path =
      "multimedia_audio_framework/remote_audio_capturer_source_unit_test"

  include_dirs = [
    "../../../../../../interfaces/inner_api/native/audiocommon/include",
    "//foundation/multimedia/audio_framework/interfaces/inner_api/native/audiocommon/include/",
    "//foundation/multimedia/audio_framework/frameworks/native/hdiadapter/source/common/",
    "//foundation/multimedia/audio_framework/frameworks/native/hdiadapter/common/include/",
    "//foundation/multimedia/audio_framework/frameworks/native/hdiadapter/source/remote/",
    "//foundation/multimedia/audio_framework/frameworks/native/audioutils/include/",
    "//foundation/multimedia/audio_framework/frameworks/native/hdiadapter/devicemanager/interface/",
    "//foundation/multimedia/audio_framework/services/audio_policy/server/include/service/common/",
  ]

  sources = [ "remote_audio_capturer_source_unit_test.cpp" ]

  cflags = [
    "-Wall",
    "-Werror",
    "-fno-access-control",
  ]

  deps = [
    "../../../../audioutils:audio_utils",
    "../../../devicemanager:audio_device_manager",
    "../../../source:remote_audio_capturer_source",
  ]

  external_deps = [
    "c_utils:utils",
    "drivers_interface_audio:libeffect_proxy_1.0",
    "googletest:gmock",
    "googletest:gtest",
    "hilog:libhilog",
    "ipc:ipc_single",
    "pulseaudio:pulse",
  ]

  part_name = "audio_framework"
  subsystem_name = "multimedia"
}
