#include <cstdint>

enum StreamClass : uint32_t {
    PA_STREAM = 0,
    FAST_STREAM,
    VOIP_STREAM,
};

enum AudioFlag : uint32_t {
    AUDIO_FLAG_NONE = 0,
    AUDIO_OUTPUT_FLAG_NORAML,
    AUDIO_OUTPUT_FLAG_DIRECT,
    AUDIO_OUTPUT_FLAG_HD,
    AUDIO_OUTPUT_FLAG_MULTICHANNEL,
    AUDIO_OUTPUT_FLAG_LOWPOWER,
    AUDIO_OUTPUT_FLAG_FAST,
    AUDIO_OUTPUT_FLAG_VOIP,
    AUDIO_OUTPUT_FLAG_HWDECODING,
    AUDIO_INPUT_FLAG_NONE = 100,
    AUDIO_INPUT_FLAG_NORAML,
    AUDIO_INPUT_FLAG_FAST,
    AUDIO_INPUT_FLAG_VOIP,
    AUDIO_INPUT_FLAG_WAKEUP,
    AUDIO_FLAG_MAX,
};