# Copyright (c) 2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/test.gni")
import("../../../../../config.gni")
module_output_path = "audio_framework/audio_framework_route/audio_adapter"

ohos_unittest("pulse_audio_service_adapter_impl_unit_test") {
  module_out_path = module_output_path
  include_dirs = [
    "../../include",
    "../../../../../interfaces/inner_api/native/audiocommon/include/",
    "../../../../../frameworks/native/audioutils/include",
    "../../../../../services/audio_service/server/include",
    "../../../../../services/audio_policy/server/include/service/common",
  ]

  cflags = [
    "-Wall",
    "-Werror",
    "-fno-access-control",
  ]

  external_deps = [
    "c_utils:utils",
    "googletest:gmock",
    "googletest:gtest",
    "hilog:libhilog",
    "hisysevent:libhisysevent",
    "ipc:ipc_single",
    "media_foundation:media_monitor_client",
    "media_foundation:media_monitor_common",
    "pulseaudio:pulse",
    "samgr:samgr_proxy",
  ]

  sources = [
    "../../src/pulse_audio_service_adapter_impl.cpp",
    "pulse_audio_service_adapter_impl_unit_test.cpp",
  ]

  deps = [
    "../../:pulse_audio_service_adapter",
    "../../../../../frameworks/native/audioutils:audio_utils",
  ]
}
