# Copyright (c) 2023 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/config/components/idl_tool/idl.gni")
import("//foundation/multimedia/audio_framework/config.gni")

idl_gen_interface("audio_policy_idl_interface") {
  sources = [
    "IStandardSpatializationStateChangeListener.idl",
    "IStandardConcurrencyStateListener.idl",
    "IStandardClientTracker.idl",
    "IStandardAudioZoneClient.idl",
  ]
  # sources_callback = [
  #   "IStandardSpatializationStateChangeListener.idl",
  # ]
  sources_common = [ ]

  #client_enable = true

  hitrace = "HITRACE_TAG_ABILITY_MANAGER"

  # log_domainid = "0xD002B21"
  # log_tag = "audio_policy"

  subsystem_name = "multimedia"
  part_name = "audio_framework"
}

config("audio_policy_sa_idl_config") {
  include_dirs = [
    # "src",
    "${target_gen_dir}",
    "${audio_framework_root}/interfaces/inner_api/native/audiocommon/include/",
    "${audio_framework_root}/frameworks/native/audiopolicy/include/",
  ]
  print("jilei4 after The value of output_values is: ", include_dirs)
}

ohos_source_set("policy_idl_sa_proxy") {
  output_values = get_target_outputs(":audio_policy_idl_interface")
  sources = filter_include(output_values,
                           [
                             "*_proxy.cpp",
                             "*_types.cpp",
                           ])

  public_configs = [ ":audio_policy_sa_idl_config" ]

  deps = [ ":audio_policy_idl_interface" ]

  cflags = [
    "-Wall",
    "-fPIC",
    "-fdata-sections",
    "-ffunction-sections",
    "-fno-asynchronous-unwind-tables",
    "-fno-unwind-tables",
    "-Os",
  ]
  if (target_cpu == "arm") {
    cflags += [ "-DBINDER_IPC_32BIT" ]
  }

  sanitize = {
    integer_overflow = true
    ubsan = true
    boundary_sanitize = true
    cfi = true
    cfi_cross_dso = true
    cfi_vcall_icall_only = true
    debug = false
  }

  external_deps = [
    "c_utils:utils",
    "hilog:libhilog",
    "hitrace:hitrace_meter",
    "ipc:ipc_single",
  ]

  part_name = "audio_framework"
  subsystem_name = "multimedia"
}

ohos_source_set("policy_idl_sa_stub") {
  output_values = get_target_outputs(":audio_policy_idl_interface")
  print("jilei1 The value of output_values is: ", output_values)
  sources = filter_include(output_values,
                           [
                             "*_stub.cpp",
                             "*_types.cpp",
                           ])
  print("jilei1 The value of output_values is: ", sources)

  public_configs = [ ":audio_policy_sa_idl_config" ]

  deps = [ ":audio_policy_idl_interface" ]

  cflags = [
    "-Wall",
    "-fPIC",
    "-fdata-sections",
    "-ffunction-sections",
    "-fno-asynchronous-unwind-tables",
    "-fno-unwind-tables",
    "-Os",
  ]
  if (target_cpu == "arm") {
    cflags += [ "-DBINDER_IPC_32BIT" ]
  }

  sanitize = {
    integer_overflow = true
    ubsan = true
    boundary_sanitize = true
    cfi = true
    cfi_cross_dso = true
    cfi_vcall_icall_only = true
    debug = false
  }

  external_deps = [
    "c_utils:utils",
    "hilog:libhilog",
    "hitrace:hitrace_meter",
    "ipc:ipc_single",
  ]

  part_name = "audio_framework"
  subsystem_name = "multimedia"
}
