# Copyright (c) 2023 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/config/components/idl_tool/idl.gni")
import("//foundation/multimedia/audio_framework/config.gni")

idl_gen_interface("audio_service_idl_interface") {
  sources = [
    "IIpcStreamListener.idl",
    "IStandardAudioServerManagerListener.idl",
    "IPolicyProviderIpc.idl",
    "ICoreServiceProviderIpc.idl",
    "IIpcStream.idl",
    "IAudioProcess.idl",
    "IProcessCb.idl",
  ]
  if (audio_framework_feature_offline_effect) {
    sources += [ "IIpcOfflineStream.idl" ]
  }
  sources_callback = [
  ]
  sources_common = [
    "AudioServiceTypes.idl"
  ]

  #client_enable = true

  hitrace = "HITRACE_TAG_ABILITY_MANAGER"

  # log_tag = "audio_service"

  subsystem_name = "multimedia"
  part_name = "audio_framework"
}

config("audio_service_sa_idl_config") {
  include_dirs = [
    "${target_gen_dir}",
    "${audio_framework_root}/interfaces/inner_api/native/audiocommon/include/",
    "${audio_framework_root}/services/audio_service/common/include/",
  ]
}

ohos_source_set("idl_sa_proxy") {
  output_values = get_target_outputs(":audio_service_idl_interface")
  sources = filter_include(output_values, [
                            "*_proxy.cpp",
                            # "*_stub.cpp",
                            "*_types.cpp",
                            # "*_callback_stub.cpp",
                          ])
  print("jileiidl proxy source =", sources)
  public_configs = [ ":audio_service_sa_idl_config" ]

  deps = [ ":audio_service_idl_interface" ]

  cflags = [
    "-Wall",
    "-fPIC",
    "-fdata-sections",
    "-ffunction-sections",
    "-fno-asynchronous-unwind-tables",
    "-fno-unwind-tables",
    "-Os",
  ]
  if (target_cpu == "arm") {
    cflags += [ "-DBINDER_IPC_32BIT" ]
  }

  sanitize = {
    integer_overflow = true
    ubsan = true
    boundary_sanitize = true
    cfi = true
    cfi_cross_dso = true
    cfi_vcall_icall_only = true
    debug = false
  }

  external_deps = [
    "c_utils:utils",
    "hilog:libhilog",
    "hitrace:hitrace_meter",
    "ipc:ipc_single",
  ]

  part_name = "audio_framework"
  subsystem_name = "multimedia"
}

ohos_source_set("idl_sa_stub") {
  output_values = get_target_outputs(":audio_service_idl_interface")
  sources = filter_include(output_values, [
                            "*_stub.cpp",
                            # "*_proxy.cpp",
                            "*_types.cpp",
                            # "*_callback_proxy.cpp",
                          ])
  print("jileiidl stub source =", sources)
  public_configs = [ ":audio_service_sa_idl_config" ]

  deps = [ ":audio_service_idl_interface" ]

  cflags = [
    "-Wall",
    "-fPIC",
    "-fdata-sections",
    "-ffunction-sections",
    "-fno-asynchronous-unwind-tables",
    "-fno-unwind-tables",
    "-Os",
  ]
  if (target_cpu == "arm") {
    cflags += [ "-DBINDER_IPC_32BIT" ]
  }

  sanitize = {
    integer_overflow = true
    ubsan = true
    boundary_sanitize = true
    cfi = true
    cfi_cross_dso = true
    cfi_vcall_icall_only = true
    debug = false
  }

  external_deps = [
    "c_utils:utils",
    "hilog:libhilog",
    "hitrace:hitrace_meter",
    "ipc:ipc_single",
  ]

  part_name = "audio_framework"
  subsystem_name = "multimedia"
}
