# Copyright (c) 2024 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/ohos.gni")
import("//build/test.gni")
import("../../../../../config.gni")

module_output_path = "audio_framework/audio_framework_route/audio_server"

ohos_unittest("audio_server_unit_test") {
  testonly = true
  module_out_path = module_output_path

  cflags = [
    "-Os",
    "-Wall",
    "-Werror",
    "-fno-access-control",]

  sources = [
    "../../../../../services/audio_service/server/src/audio_effect_server.cpp",
    "../../../../../services/audio_service/server/src/audio_manager_listener.cpp",
    "../../../../../services/audio_service/server/src/audio_resource_service.cpp",
    "../../../../../services/audio_service/server/src/audio_server.cpp",
    "../../../../../services/audio_service/server/src/audio_server_asr.cpp",
    "../../../../../services/audio_service/server/src/audio_server_dump.cpp",
    "../../../../../services/audio_service/server/src/audio_server_effect.cpp",
    "../../../../../services/audio_service/server/src/audio_server_hpae_dump.cpp",
    "../../../../../services/audio_service/server/src/audio_workgroup.cpp",
    "../../../../../services/audio_service/server/src/config/audio_param_parser.cpp",
    "./src/audio_server_unit_test.cpp",
  ]

  include_dirs = [
    "../../../server/include",
    "../../../../audio_service/common/include",
    "../../../../audio_service/common",
    "./include",
    "../../../../../interfaces/inner_api/native/audiocommon/include",
    "../../../../../frameworks/native/audioinnercall/include",
    "../../../../../frameworks/native/audioclock/include",
    "../../../../../services/audio_service/server/include",
    "../../../../../services/audio_policy/client/include",
  ]

  configs = [ "../../../../../services/audio_service:audio_service_config" ]

  deps = [
    "${audio_framework_root}/services/audio_service/idl:audio_framework_interface",
    "../../../../../frameworks/native/audioclock:audio_clock",
    "../../../../../services/audio_service:audio_service",
    "../../../../audio_service:audio_process_service",
    "../../../../audio_service:audio_common",
    "../../../../../frameworks/native/audioeffect:audio_effect",
    "../../../../../frameworks/native/audioinnercall:audio_inner_call",
    "../../../../../frameworks/native/audioschedule:audio_schedule",
    "../../../../../frameworks/native/audioutils:audio_utils",
    "../../../../../frameworks/native/audioutils:audio_xml_utils",
    "../../../../../frameworks/native/hdiadapter_new:hdiadapter_new",
    "../../../../audio_engine:audio_engine_manager",
  ]

  external_deps = [
    "ability_base:want",
    "access_token:libaccesstoken_sdk",
    "bundle_framework:appexecfwk_base",
    "bundle_framework:appexecfwk_core",
    "c_utils:utils",
    "drivers_interface_audio:libeffect_proxy_1.0",
    "frame_aware_sched:rtg_interface",
    "hicollie:libhicollie",
    "hilog:libhilog",
    "hisysevent:libhisysevent",
    "init:libbegetutil",
    "ipc:ipc_single",
    "media_foundation:media_monitor_client",
    "media_foundation:media_monitor_common",
    "pulseaudio:pulse",
    "pulseaudio:pulseaudio",
    "qos_manager:concurrent_task_client",
    "safwk:system_ability_fwk",
    "samgr:samgr_proxy",
  ]

  cflags_cc = cflags
  cflags_cc += [ "-std=c++20" ]
}
