# Copyright (c) 2021-2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/ohos.gni")
import("../../accessibility.gni")
import("../../appgallery.gni")
import("../../audio_framework_test_sources.gni")
import("../../av_session.gni")
import("../../bluetooth_part.gni")
import("../../config.gni")

group("audio_policy_packages") {
  deps = [
    ":audio_affinity_config",
    ":audio_converter_config",
    ":audio_device_config",
    ":audio_interrupt_policy_config",
    ":audio_policy_global_config",
    ":audio_policy_service",
    ":audio_strategy_router",
    ":audio_usage_strategy",
    ":audio_volume_config",
    "server/domain/volume:audio_safe_volume_notification_impl",
  ]

  if (audio_framework_feature_dtmf_tone) {
    deps += [ ":audio_tone_dtmf_config" ]
  }
}

config("audio_policy_public_config") {
  include_dirs = [
    "../audio_service:audio_service_client_include",
    "server/domain/interrupt:audio_interrupt_include",
    "server/domain/volume:audio_volume_include",
    "server/domain/pipe:audio_pipe_include",
    "server/infra/appclient:infra_appclient_include",
    "server/infra/async_action_handler:async_action_include",
    "server/infra/config/parser:infra_parser_include",
    "server/infra/datashare:infra_datashare_include",
    "server/infra/ipc_proxy:infra_ipc_proxy_include",
    "server/infra/state_monitor:infra_state_monitor_include",
    "server/proxy:server_proxy_include",
    "server/domain/zone:audio_zone_include",
    "server/common:server_common_include",
    "server/service/service_main:service_main_include",
    "server/domain/stream:audio_stream_collector_include",
    "server/domain/device:audio_device_include",
    "server/domain/effect:audio_effect_include",
    "server/domain/router:audio_router_include",
    "server/domain/tone:audio_tone_include",
    "server/domain/session:audio_session_include",
    "server/stub:server_stub_include",
  ]

  cflags = [
    "-Wall",
    "-Werror",
  ]

  if (target_cpu == "arm") {
    cflags += [ "-DBINDER_IPC_32BIT" ]
  }

  if (accessibility_enable == true) {
    cflags += [ "-DACCESSIBILITY_ENABLE" ]
  }

  if (bluetooth_part_enable == true) {
    cflags += [ "-DBLUETOOTH_ENABLE" ]
  }

  if (avsession_part_enable == true && !(use_libfuzzer || use_clang_coverage)) {
    cflags += [ "-DAVSESSION_ENABLE" ]
  }

  ldflags = [ "-Wl" ]
}

ohos_shared_library("audio_setting_provider") {
  stack_protector_ret = true
  sanitize = {
    cfi = true
    cfi_cross_dso = true
    cfi_vcall_icall_only = true
    debug = false
    integer_overflow = true
    ubsan = true
    boundary_sanitize = true
  }
  install_enable = true

  include_dirs = [
    "../../services/audio_policy/server/infra/datashare/include",
    "../../services/audio_policy/server/domain/device/src/pnp",
    "../../interfaces/inner_api/native/audiocommon/include",
  ]

  sources = [ "server/infra/datashare/src/audio_setting_provider.cpp" ]

  deps = [ "../../frameworks/native/audioutils:audio_utils" ]

  external_deps = [
    "c_utils:utils",
    "data_share:datashare_common",
    "data_share:datashare_consumer",
    "hilog:libhilog",
    "ipc:ipc_single",
    "os_account:os_account_innerkits",
    "samgr:samgr_proxy",
  ]
  cflags = [ "-Os" ]
  cflags_cc = cflags

  defines = []
  if (audio_framework_feature_support_os_account) {
    defines += [ "SUPPORT_USER_ACCOUNT" ]
  }

  part_name = "audio_framework"
  subsystem_name = "multimedia"
}

audio_ohos_library("audio_policy_service") {
  stack_protector_ret = true
  sanitize = {
    cfi = true
    cfi_cross_dso = true
    cfi_vcall_icall_only = true
    debug = false
    integer_overflow = true
    ubsan = true
    boundary_sanitize = true
  }
  install_enable = true
  deps = [
    "../audio_service:audio_service_client_static_library",
    "server/domain/interrupt:audio_interrupt_static_library",
    "server/domain/volume:audio_volume_static_library",
    "server/domain/pipe:audio_pipe_static_library",
    "server/infra/appclient:infra_appclient_static_library",
    "server/infra/async_action_handler:async_action_static_library",
    "server/infra/config/parser:infra_parser_static_library",
    "server/infra/datashare:infra_datashare_static_library",
    "server/infra/ipc_proxy:infra_ipc_proxy_static_library",
    "server/infra/state_monitor:infra_state_monitor_static_library",
    "server/proxy:server_proxy_static_library",
    "server/domain/zone:audio_zone_static_library",
    "server/common:server_common_static_library",
    "server/service/service_main:service_main_static_library",
    "server/domain/stream:audio_stream_collector",
    "server/domain/device:audio_device_static_library",
    "server/domain/effect:audio_effect_static_library",
    "server/domain/router:audio_router_static_library",
    "server/domain/tone:audio_tone_static_library",
    "server/domain/session:audio_session_static_library",
    "server/stub:server_stub_static_library",

  ]

  public_configs = [ ":audio_policy_public_config" ]

  external_deps = [
    "hilog:libhilog",
  ]

  public_external_deps = [ "ffrt:libffrt" ]

  public_external_deps += [
    "libxml2:libxml2",
    "openssl:libcrypto_shared",
  ]

  cflags = [ "-Os" ]
  cflags_cc = cflags
  subsystem_name = "multimedia"
  part_name = "audio_framework"
  version_script = "libaudio_policy_service.versionscript"
}

ohos_prebuilt_etc("audio_interrupt_policy_config") {
  source = "server/infra/config/file/audio_interrupt_policy_config.xml"

  subsystem_name = "multimedia"
  relative_install_dir = "audio"
  part_name = "audio_framework"
}

ohos_prebuilt_etc("audio_strategy_router") {
  source = "server/infra/config/file/audio_strategy_router.xml"

  subsystem_name = "multimedia"
  relative_install_dir = "audio"
  part_name = "audio_framework"
}

ohos_prebuilt_etc("audio_usage_strategy") {
  source = "server/infra/config/file/audio_usage_strategy.xml"

  subsystem_name = "multimedia"
  relative_install_dir = "audio"
  part_name = "audio_framework"
}

ohos_prebuilt_etc("audio_device_config") {
  source = "server/infra/config/file/audio_device_privacy.xml"

  subsystem_name = "multimedia"
  relative_install_dir = "audio"
  part_name = "audio_framework"
}

ohos_prebuilt_etc("audio_volume_config") {
  source = "server/infra/config/file/audio_volume_config.xml"

  subsystem_name = "multimedia"
  relative_install_dir = "audio"
  part_name = "audio_framework"
}

ohos_prebuilt_etc("audio_affinity_config") {
  source = "server/infra/config/file/audio_affinity_config.xml"

  subsystem_name = "multimedia"
  relative_install_dir = "audio"
  part_name = "audio_framework"
}

ohos_prebuilt_etc("audio_policy_global_config") {
  source = "server/infra/config/file/audio_policy_global_config.xml"

  subsystem_name = "multimedia"
  relative_install_dir = "audio"
  part_name = "audio_framework"
}

if (audio_framework_feature_dtmf_tone) {
  ohos_prebuilt_etc("audio_tone_dtmf_config") {
    source = "server/infra/config/file/audio_tone_dtmf_config.xml"

    subsystem_name = "multimedia"
    relative_install_dir = "audio"
    part_name = "audio_framework"
  }
}

ohos_prebuilt_etc("audio_converter_config") {
  source = "server/infra/config/file/audio_converter_config.xml"

  subsystem_name = "multimedia"
  relative_install_dir = "audio"
  part_name = "audio_framework"
}

ohos_prebuilt_etc("audio_config.para") {
  source = "etc/audio_config.para"
  subsystem_name = "multimedia"
  part_name = "audio_framework"
  module_install_dir = "etc/param"
}

ohos_prebuilt_etc("audio_config.para.dac") {
  source = "etc/audio_config.para.dac"
  subsystem_name = "multimedia"
  part_name = "audio_framework"
  module_install_dir = "etc/param"
}

config("audio_policy_client_config") {
  include_dirs = [
    "client/proxy/include",
    "client/stub/include",
    "common/include",
    "client/interface",
    "server/include",
    "server/proxy/include",
    "server/stub/include",
    "server/service/service_main/include",
    "../audio_service/client/include",
    "../audio_service/common/include",
    "../../frameworks/native/audiodefinitions/include",
    "../../frameworks/native/audiopolicy/include",
    "../../interfaces/inner_api/native/audiocommon/include",
    "../../interfaces/inner_api/native/audiomanager/include",
  ]

  cflags = [
    "-Wall",
    "-Werror",
  ]

  if (target_cpu == "arm") {
    cflags += [ "-DBINDER_IPC_32BIT" ]
  }
}

audio_ohos_library("audio_policy_client") {
  branch_protector_ret = "pac_ret"
  install_enable = true

  defines = []
  if (audio_framework_feature_dtmf_tone) {
    defines += [ "FEATURE_DTMF_TONE" ]
  }

  if (audio_framework_feature_inner_capturer) {
    defines += [ "HAS_FEATURE_INNERCAPTURER" ]
  }

  sources = [
    "../audio_policy/server/domain/device/src/audio_device_descriptor.cpp",
    "../audio_service/client/src/audio_filter.cpp",
    "../audio_service/client/src/microphone_descriptor.cpp",
    "client/proxy/src/audio_policy_callback_proxy.cpp",
    "client/proxy/src/audio_policy_microphone_proxy.cpp",
    "client/proxy/src/audio_policy_proxy.cpp",
    "client/proxy/src/audio_policy_volume_proxy.cpp",
    "client/proxy/src/audio_policy_zone_proxy.cpp",
    "client/service/src/audio_policy_manager.cpp",
    "client/service/src/audio_policy_manager_device.cpp",
    "client/service/src/audio_policy_manager_zone.cpp",
    "client/service/src/audio_zone_manager.cpp",
    "server/domain/volume/src/audio_volume_group_info.cpp",
    "client/stub/src/audio_anahs_manager_listener_stub.cpp",
    "client/stub/src/audio_client_tracker_callback_stub.cpp",
    "client/stub/src/audio_concurrency_state_listener_stub.cpp",
    "client/stub/src/audio_policy_client_stub.cpp",
    "client/stub/src/audio_policy_client_stub_impl.cpp",
    "client/stub/src/audio_policy_manager_listener_stub.cpp",
    "client/stub/src/audio_routing_manager_listener_stub.cpp",
    "client/stub/src/audio_spatialization_state_change_listener_stub.cpp",
    "client/stub/src/audio_zone_client.cpp",
    "client/stub/src/sle_audio_operation_callback_stub.cpp",
  ]

  deps = [
    "../../frameworks/native/audiodefinitions:audio_definitions",
    "../../frameworks/native/audioutils:audio_utils",
  ]

  public_configs = [ ":audio_policy_client_config" ]

  include_dirs = [ "../../frameworks/native/audioutils/include" ]

  external_deps = [
    "bounds_checking_function:libsec_shared",
    "c_utils:utils",
    "eventhandler:libeventhandler",
    "hilog:libhilog",
    "init:libbegetutil",
    "ipc:ipc_single",
    "samgr:samgr_proxy",
  ]
  subsystem_name = "multimedia"
  innerapi_tags = [ "platformsdk" ]
  cflags = [ "-Os" ]
  cflags_cc = cflags
  part_name = "audio_framework"

  ldflags = [ "-Wl,-Bsymbolic" ]
  version_script = "libaudio_policy_client.versionscript"
}

group("audio_policy_test_packages") {
  testonly = true

  deps = [
    ":audio_dump_test",
    ":audio_policy_test",
    "test:audio_policy_unittest_packages",
  ]
}

ohos_executable("audio_dump_test") {
  install_enable = false
  sanitize = {
    cfi = true
    cfi_cross_dso = true
    cfi_vcall_icall_only = true
    debug = false
    integer_overflow = true
    ubsan = true
    boundary_sanitize = true
  }
  sources = [ "test/example/audio_dump_test.cpp" ]

  configs = [ ":audio_policy_client_config" ]

  deps = [
    "../audio_policy:audio_policy_client",
    "../audio_service:audio_client",
  ]

  include_dirs = []

  external_deps = [
    "bounds_checking_function:libsec_shared",
    "c_utils:utils",
    "hilog:libhilog",
    "ipc:ipc_single",
  ]

  part_name = "audio_framework"
  subsystem_name = "multimedia"
}

ohos_executable("audio_policy_test") {
  install_enable = false

  sources = [ "test/example/audio_policy_test.cpp" ]

  configs = [ ":audio_policy_client_config" ]

  deps = [
    "../audio_policy:audio_foundation",
    "../audio_policy:audio_policy_client",
    "../audio_service:audio_client",
  ]

  include_dirs = []

  external_deps = [
    "bounds_checking_function:libsec_shared",
    "c_utils:utils",
    "hilog:libhilog",
    "ipc:ipc_single",
  ]

  part_name = "audio_framework"
  subsystem_name = "multimedia"
}

config("audio_foundation_public_config") {
  include_dirs = [
    "util/include",
    "server/domain/device/include",
    "server/domain/effect/include",
    "../audio_service/util/include",
    "../../interfaces/inner_api/native/audiocommon/include",
    "../../interfaces/inner_api/native/audiomanager/include",
    "../../frameworks/native/audiopolicy/include",
  ]
}

ohos_shared_library("audio_foundation") {
  branch_protector_ret = "pac_ret"
  sanitize = {
    cfi = true
    cfi_cross_dso = true
    cfi_vcall_icall_only = true
    debug = false
    integer_overflow = true
    ubsan = true
    boundary_sanitize = true
  }
  install_enable = true
  sources = [
    "../audio_service/client/src/audio_filter.cpp",
    "server/domain/device/src/audio_device_descriptor.cpp",
    "server/domain/device/src/audio_device_type.cpp",
    "server/domain/effect/src/audio_effect_map.cpp",
  ]

  public_configs = [ ":audio_foundation_public_config" ]

  deps = [
    "../../frameworks/native/audioutils:audio_utils",
    "../audio_policy:audio_policy_client",
    "../audio_service:audio_common",
  ]

  external_deps = [ "hilog:libhilog" ]

  public_external_deps = [ "c_utils:utils" ]

  cflags = [ "-Os" ]
  cflags_cc = cflags

  defines = []
  if (audio_framework_feature_detect_soundbox) {
    defines += [ "DETECT_SOUNDBOX" ]
  }

  innerapi_tags = [ "platformsdk" ]
  subsystem_name = "multimedia"
  part_name = "audio_framework"
}

config("audio_manager_client_public_config") {
  include_dirs = [
    "util/include",
    "client/service/include",
    "server/domain/device/include",
    "server/domain/effect/include",
    "../../frameworks/native/audiodefinitions/include",
    "../../frameworks/native/audiodefinitions/include/common",
    "../../frameworks/native/hdiadapter_new/include/common",
  ]
}

ohos_shared_library("audio_manager_client") {
  branch_protector_ret = "pac_ret"
  sanitize = {
    cfi = true
    cfi_cross_dso = true
    cfi_vcall_icall_only = true
    debug = false
    integer_overflow = true
    ubsan = true
    boundary_sanitize = true
  }
  install_enable = true
  sources = [
    "../audio_service/client/src/audio_anahs_manager.cpp",
    "client/service/src/audio_general_manager.cpp",
  ]

  public_configs = [ ":audio_manager_client_public_config" ]

  deps = [
    ":audio_foundation",
    ":audio_policy_client",
    ":audio_policy_common",
    "../../frameworks/native/audioutils:audio_utils",
    "../audio_service:audio_common",
  ]

  external_deps = [
    "bundle_framework:appexecfwk_base",
    "bundle_framework:appexecfwk_core",
    "eventhandler:libeventhandler",
    "hicollie:libhicollie",
    "hilog:libhilog",
    "ipc:ipc_single",
    "samgr:samgr_proxy",
  ]

  defines = []
  if (audio_framework_feature_inner_capturer) {
    defines += [ "HAS_FEATURE_INNERCAPTURER" ]
  }

  cflags = [ "-Os" ]
  cflags_cc = cflags

  innerapi_tags = [ "platformsdk" ]
  subsystem_name = "multimedia"
  part_name = "audio_framework"
}

config("audio_policy_common_public_config") {
  include_dirs = [
    "../../interfaces/inner_api/native/audiomanager/include",
    "../../interfaces/inner_api/native/audiocommon/include",
    "../audio_service/client/include",
  ]
}

ohos_shared_library("audio_policy_common") {
  branch_protector_ret = "pac_ret"
  sanitize = {
    cfi = true
    cfi_cross_dso = true
    cfi_vcall_icall_only = true
    debug = false
    integer_overflow = true
    ubsan = true
    boundary_sanitize = true
  }
  install_enable = true
  sources = [
    "../audio_service/client/src/audio_focus_info_change_callback_impl.cpp",
    "../audio_service/client/src/resource_manager_adapter.cpp",
  ]

  public_configs = [ ":audio_policy_common_public_config" ]

  external_deps = [
    "c_utils:utils",
    "common_event_service:cesfwk_innerkits",
    "hilog:libhilog",
    "i18n:intl_util",
    "ipc:ipc_core",
    "resource_management:global_resmgr",
  ]

  cflags = [ "-Os" ]
  cflags_cc = cflags

  innerapi_tags = [ "platformsdk" ]
  subsystem_name = "multimedia"
  part_name = "audio_framework"
}

config("audio_policy_ipc_config") {
  include_dirs = [
    "common/include",
  ]
}

ohos_shared_library("audio_policy_ipc") {
  branch_protector_ret = "pac_ret"
  sanitize = {
    cfi = true
    cfi_cross_dso = true
    cfi_vcall_icall_only = true
    debug = false
    integer_overflow = true
    ubsan = true
    boundary_sanitize = true
  }
  install_enable = true
  sources = []

  public_configs = [ ":audio_policy_ipc_config" ]

  external_deps = []

  cflags = [ "-Os" ]
  cflags_cc = cflags

  innerapi_tags = [ "platformsdk" ]
  subsystem_name = "multimedia"
  part_name = "audio_framework"
}
